-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
-- Date        : Thu May 22 09:10:10 2025
-- Host        : xcosswbld25 running 64-bit Ubuntu 22.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /scratch/rfrefdesigns_2025.1_0522_1_ZCU208/trunk/HW/48_trdPllOnddr_dacddr_adcmts_ex/rfip_ex/rfip_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_adc_sink_i_0/rfdc_ex_adc_sink_i_0_stub.vhdl
-- Design      : rfdc_ex_adc_sink_i_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu48dr-fsvg1517-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity rfdc_ex_adc_sink_i_0 is
  Port ( 
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 19 downto 0 );
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awready : out STD_LOGIC;
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wready : out STD_LOGIC;
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bready : in STD_LOGIC;
    s_axi_araddr : in STD_LOGIC_VECTOR ( 19 downto 0 );
    s_axi_arvalid : in STD_LOGIC;
    s_axi_arready : out STD_LOGIC;
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rready : in STD_LOGIC;
    s00_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s00_tvalid : in STD_LOGIC;
    m00_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m00_tvalid : out STD_LOGIC;
    m00_tready : in STD_LOGIC;
    s01_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s01_tvalid : in STD_LOGIC;
    m01_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m01_tvalid : out STD_LOGIC;
    m01_tready : in STD_LOGIC;
    s02_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s02_tvalid : in STD_LOGIC;
    m02_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m02_tvalid : out STD_LOGIC;
    m02_tready : in STD_LOGIC;
    s03_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s03_tvalid : in STD_LOGIC;
    m03_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m03_tvalid : out STD_LOGIC;
    m03_tready : in STD_LOGIC;
    s10_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s10_tvalid : in STD_LOGIC;
    m10_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m10_tvalid : out STD_LOGIC;
    m10_tready : in STD_LOGIC;
    s11_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s11_tvalid : in STD_LOGIC;
    m11_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m11_tvalid : out STD_LOGIC;
    m11_tready : in STD_LOGIC;
    s12_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s12_tvalid : in STD_LOGIC;
    m12_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m12_tvalid : out STD_LOGIC;
    m12_tready : in STD_LOGIC;
    s13_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s13_tvalid : in STD_LOGIC;
    m13_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m13_tvalid : out STD_LOGIC;
    m13_tready : in STD_LOGIC;
    s20_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s20_tvalid : in STD_LOGIC;
    m20_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m20_tvalid : out STD_LOGIC;
    m20_tready : in STD_LOGIC;
    s21_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s21_tvalid : in STD_LOGIC;
    m21_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m21_tvalid : out STD_LOGIC;
    m21_tready : in STD_LOGIC;
    s22_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s22_tvalid : in STD_LOGIC;
    m22_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m22_tvalid : out STD_LOGIC;
    m22_tready : in STD_LOGIC;
    s23_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s23_tvalid : in STD_LOGIC;
    m23_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m23_tvalid : out STD_LOGIC;
    m23_tready : in STD_LOGIC;
    s30_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s30_tvalid : in STD_LOGIC;
    m30_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m30_tvalid : out STD_LOGIC;
    m30_tready : in STD_LOGIC;
    s31_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s31_tvalid : in STD_LOGIC;
    m31_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m31_tvalid : out STD_LOGIC;
    m31_tready : in STD_LOGIC;
    s32_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s32_tvalid : in STD_LOGIC;
    m32_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m32_tvalid : out STD_LOGIC;
    m32_tready : in STD_LOGIC;
    s33_tdata : in STD_LOGIC_VECTOR ( 191 downto 0 );
    s33_tvalid : in STD_LOGIC;
    m33_tdata : out STD_LOGIC_VECTOR ( 191 downto 0 );
    m33_tvalid : out STD_LOGIC;
    m33_tready : in STD_LOGIC;
    s0_axis_clock : in STD_LOGIC;
    s0_div2_axis_clock : in STD_LOGIC;
    s1_axis_clock : in STD_LOGIC;
    s1_div2_axis_clock : in STD_LOGIC;
    s2_axis_clock : in STD_LOGIC;
    s2_div2_axis_clock : in STD_LOGIC;
    s3_axis_clock : in STD_LOGIC;
    s3_div2_axis_clock : in STD_LOGIC;
    hw_trigger_0 : in STD_LOGIC;
    hw_trigger_en_0 : in STD_LOGIC;
    hw_trigger_1 : in STD_LOGIC;
    hw_trigger_en_1 : in STD_LOGIC;
    hw_trigger_2 : in STD_LOGIC;
    hw_trigger_en_2 : in STD_LOGIC;
    hw_trigger_3 : in STD_LOGIC;
    hw_trigger_en_3 : in STD_LOGIC;
    s_axi_aclk : in STD_LOGIC;
    s_axi_aresetn : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of rfdc_ex_adc_sink_i_0 : entity is "rfdc_ex_adc_sink_i_0,exdes_rfadc_data_bram_capture,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of rfdc_ex_adc_sink_i_0 : entity is "rfdc_ex_adc_sink_i_0,exdes_rfadc_data_bram_capture,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=exdes_rfadc_data_bram_capture,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,mem_size=262144,axi_addr_top=19,use_div2_clk_0=0,use_div2_clk_1=0,use_div2_clk_2=0,use_div2_clk_3=0}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of rfdc_ex_adc_sink_i_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of rfdc_ex_adc_sink_i_0 : entity is "module_ref";
end rfdc_ex_adc_sink_i_0;

architecture stub of rfdc_ex_adc_sink_i_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_awaddr[19:0],s_axi_awvalid,s_axi_awready,s_axi_wdata[31:0],s_axi_wvalid,s_axi_wready,s_axi_wstrb[3:0],s_axi_bresp[1:0],s_axi_bvalid,s_axi_bready,s_axi_araddr[19:0],s_axi_arvalid,s_axi_arready,s_axi_rdata[31:0],s_axi_rresp[1:0],s_axi_rvalid,s_axi_rready,s00_tdata[191:0],s00_tvalid,m00_tdata[191:0],m00_tvalid,m00_tready,s01_tdata[191:0],s01_tvalid,m01_tdata[191:0],m01_tvalid,m01_tready,s02_tdata[191:0],s02_tvalid,m02_tdata[191:0],m02_tvalid,m02_tready,s03_tdata[191:0],s03_tvalid,m03_tdata[191:0],m03_tvalid,m03_tready,s10_tdata[191:0],s10_tvalid,m10_tdata[191:0],m10_tvalid,m10_tready,s11_tdata[191:0],s11_tvalid,m11_tdata[191:0],m11_tvalid,m11_tready,s12_tdata[191:0],s12_tvalid,m12_tdata[191:0],m12_tvalid,m12_tready,s13_tdata[191:0],s13_tvalid,m13_tdata[191:0],m13_tvalid,m13_tready,s20_tdata[191:0],s20_tvalid,m20_tdata[191:0],m20_tvalid,m20_tready,s21_tdata[191:0],s21_tvalid,m21_tdata[191:0],m21_tvalid,m21_tready,s22_tdata[191:0],s22_tvalid,m22_tdata[191:0],m22_tvalid,m22_tready,s23_tdata[191:0],s23_tvalid,m23_tdata[191:0],m23_tvalid,m23_tready,s30_tdata[191:0],s30_tvalid,m30_tdata[191:0],m30_tvalid,m30_tready,s31_tdata[191:0],s31_tvalid,m31_tdata[191:0],m31_tvalid,m31_tready,s32_tdata[191:0],s32_tvalid,m32_tdata[191:0],m32_tvalid,m32_tready,s33_tdata[191:0],s33_tvalid,m33_tdata[191:0],m33_tvalid,m33_tready,s0_axis_clock,s0_div2_axis_clock,s1_axis_clock,s1_div2_axis_clock,s2_axis_clock,s2_div2_axis_clock,s3_axis_clock,s3_div2_axis_clock,hw_trigger_0,hw_trigger_en_0,hw_trigger_1,hw_trigger_en_1,hw_trigger_2,hw_trigger_en_2,hw_trigger_3,hw_trigger_en_3,s_axi_aclk,s_axi_aresetn";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s_axi AWADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_awaddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_awaddr : signal is "XIL_INTERFACENAME s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 57500000, ID_WIDTH 0, ADDR_WIDTH 20, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_s_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi AWVALID";
  attribute X_INTERFACE_INFO of s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s_axi AWREADY";
  attribute X_INTERFACE_INFO of s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s_axi WDATA";
  attribute X_INTERFACE_INFO of s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi WVALID";
  attribute X_INTERFACE_INFO of s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s_axi WREADY";
  attribute X_INTERFACE_INFO of s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s_axi WSTRB";
  attribute X_INTERFACE_INFO of s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s_axi BRESP";
  attribute X_INTERFACE_INFO of s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi BVALID";
  attribute X_INTERFACE_INFO of s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s_axi BREADY";
  attribute X_INTERFACE_INFO of s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s_axi ARADDR";
  attribute X_INTERFACE_INFO of s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi ARVALID";
  attribute X_INTERFACE_INFO of s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s_axi ARREADY";
  attribute X_INTERFACE_INFO of s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s_axi RDATA";
  attribute X_INTERFACE_INFO of s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s_axi RRESP";
  attribute X_INTERFACE_INFO of s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi RVALID";
  attribute X_INTERFACE_INFO of s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s_axi RREADY";
  attribute X_INTERFACE_INFO of s00_tdata : signal is "xilinx.com:interface:axis:1.0 s00 TDATA";
  attribute X_INTERFACE_MODE of s00_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s00_tdata : signal is "XIL_INTERFACENAME s00, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s00_tvalid : signal is "xilinx.com:interface:axis:1.0 s00 TVALID";
  attribute X_INTERFACE_MODE of s00_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m00_tdata : signal is "xilinx.com:interface:axis:1.0 m00 TDATA";
  attribute X_INTERFACE_MODE of m00_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m00_tdata : signal is "XIL_INTERFACENAME m00, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m00_tvalid : signal is "xilinx.com:interface:axis:1.0 m00 TVALID";
  attribute X_INTERFACE_INFO of m00_tready : signal is "xilinx.com:interface:axis:1.0 m00 TREADY";
  attribute X_INTERFACE_INFO of s01_tdata : signal is "xilinx.com:interface:axis:1.0 s01 TDATA";
  attribute X_INTERFACE_MODE of s01_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s01_tdata : signal is "XIL_INTERFACENAME s01, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s01_tvalid : signal is "xilinx.com:interface:axis:1.0 s01 TVALID";
  attribute X_INTERFACE_MODE of s01_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m01_tdata : signal is "xilinx.com:interface:axis:1.0 m01 TDATA";
  attribute X_INTERFACE_MODE of m01_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m01_tdata : signal is "XIL_INTERFACENAME m01, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m01_tvalid : signal is "xilinx.com:interface:axis:1.0 m01 TVALID";
  attribute X_INTERFACE_INFO of m01_tready : signal is "xilinx.com:interface:axis:1.0 m01 TREADY";
  attribute X_INTERFACE_INFO of s02_tdata : signal is "xilinx.com:interface:axis:1.0 s02 TDATA";
  attribute X_INTERFACE_MODE of s02_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s02_tdata : signal is "XIL_INTERFACENAME s02, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s02_tvalid : signal is "xilinx.com:interface:axis:1.0 s02 TVALID";
  attribute X_INTERFACE_MODE of s02_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m02_tdata : signal is "xilinx.com:interface:axis:1.0 m02 TDATA";
  attribute X_INTERFACE_MODE of m02_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m02_tdata : signal is "XIL_INTERFACENAME m02, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m02_tvalid : signal is "xilinx.com:interface:axis:1.0 m02 TVALID";
  attribute X_INTERFACE_INFO of m02_tready : signal is "xilinx.com:interface:axis:1.0 m02 TREADY";
  attribute X_INTERFACE_INFO of s03_tdata : signal is "xilinx.com:interface:axis:1.0 s03 TDATA";
  attribute X_INTERFACE_MODE of s03_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s03_tdata : signal is "XIL_INTERFACENAME s03, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s03_tvalid : signal is "xilinx.com:interface:axis:1.0 s03 TVALID";
  attribute X_INTERFACE_MODE of s03_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m03_tdata : signal is "xilinx.com:interface:axis:1.0 m03 TDATA";
  attribute X_INTERFACE_MODE of m03_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m03_tdata : signal is "XIL_INTERFACENAME m03, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m03_tvalid : signal is "xilinx.com:interface:axis:1.0 m03 TVALID";
  attribute X_INTERFACE_INFO of m03_tready : signal is "xilinx.com:interface:axis:1.0 m03 TREADY";
  attribute X_INTERFACE_INFO of s10_tdata : signal is "xilinx.com:interface:axis:1.0 s10 TDATA";
  attribute X_INTERFACE_MODE of s10_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s10_tdata : signal is "XIL_INTERFACENAME s10, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s10_tvalid : signal is "xilinx.com:interface:axis:1.0 s10 TVALID";
  attribute X_INTERFACE_MODE of s10_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m10_tdata : signal is "xilinx.com:interface:axis:1.0 m10 TDATA";
  attribute X_INTERFACE_MODE of m10_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m10_tdata : signal is "XIL_INTERFACENAME m10, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m10_tvalid : signal is "xilinx.com:interface:axis:1.0 m10 TVALID";
  attribute X_INTERFACE_INFO of m10_tready : signal is "xilinx.com:interface:axis:1.0 m10 TREADY";
  attribute X_INTERFACE_INFO of s11_tdata : signal is "xilinx.com:interface:axis:1.0 s11 TDATA";
  attribute X_INTERFACE_MODE of s11_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s11_tdata : signal is "XIL_INTERFACENAME s11, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s11_tvalid : signal is "xilinx.com:interface:axis:1.0 s11 TVALID";
  attribute X_INTERFACE_MODE of s11_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m11_tdata : signal is "xilinx.com:interface:axis:1.0 m11 TDATA";
  attribute X_INTERFACE_MODE of m11_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m11_tdata : signal is "XIL_INTERFACENAME m11, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m11_tvalid : signal is "xilinx.com:interface:axis:1.0 m11 TVALID";
  attribute X_INTERFACE_INFO of m11_tready : signal is "xilinx.com:interface:axis:1.0 m11 TREADY";
  attribute X_INTERFACE_INFO of s12_tdata : signal is "xilinx.com:interface:axis:1.0 s12 TDATA";
  attribute X_INTERFACE_MODE of s12_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s12_tdata : signal is "XIL_INTERFACENAME s12, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s12_tvalid : signal is "xilinx.com:interface:axis:1.0 s12 TVALID";
  attribute X_INTERFACE_MODE of s12_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m12_tdata : signal is "xilinx.com:interface:axis:1.0 m12 TDATA";
  attribute X_INTERFACE_MODE of m12_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m12_tdata : signal is "XIL_INTERFACENAME m12, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m12_tvalid : signal is "xilinx.com:interface:axis:1.0 m12 TVALID";
  attribute X_INTERFACE_INFO of m12_tready : signal is "xilinx.com:interface:axis:1.0 m12 TREADY";
  attribute X_INTERFACE_INFO of s13_tdata : signal is "xilinx.com:interface:axis:1.0 s13 TDATA";
  attribute X_INTERFACE_MODE of s13_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s13_tdata : signal is "XIL_INTERFACENAME s13, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s13_tvalid : signal is "xilinx.com:interface:axis:1.0 s13 TVALID";
  attribute X_INTERFACE_MODE of s13_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m13_tdata : signal is "xilinx.com:interface:axis:1.0 m13 TDATA";
  attribute X_INTERFACE_MODE of m13_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m13_tdata : signal is "XIL_INTERFACENAME m13, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m13_tvalid : signal is "xilinx.com:interface:axis:1.0 m13 TVALID";
  attribute X_INTERFACE_INFO of m13_tready : signal is "xilinx.com:interface:axis:1.0 m13 TREADY";
  attribute X_INTERFACE_INFO of s20_tdata : signal is "xilinx.com:interface:axis:1.0 s20 TDATA";
  attribute X_INTERFACE_MODE of s20_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s20_tdata : signal is "XIL_INTERFACENAME s20, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s20_tvalid : signal is "xilinx.com:interface:axis:1.0 s20 TVALID";
  attribute X_INTERFACE_MODE of s20_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m20_tdata : signal is "xilinx.com:interface:axis:1.0 m20 TDATA";
  attribute X_INTERFACE_MODE of m20_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m20_tdata : signal is "XIL_INTERFACENAME m20, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m20_tvalid : signal is "xilinx.com:interface:axis:1.0 m20 TVALID";
  attribute X_INTERFACE_INFO of m20_tready : signal is "xilinx.com:interface:axis:1.0 m20 TREADY";
  attribute X_INTERFACE_INFO of s21_tdata : signal is "xilinx.com:interface:axis:1.0 s21 TDATA";
  attribute X_INTERFACE_MODE of s21_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s21_tdata : signal is "XIL_INTERFACENAME s21, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s21_tvalid : signal is "xilinx.com:interface:axis:1.0 s21 TVALID";
  attribute X_INTERFACE_MODE of s21_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m21_tdata : signal is "xilinx.com:interface:axis:1.0 m21 TDATA";
  attribute X_INTERFACE_MODE of m21_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m21_tdata : signal is "XIL_INTERFACENAME m21, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m21_tvalid : signal is "xilinx.com:interface:axis:1.0 m21 TVALID";
  attribute X_INTERFACE_INFO of m21_tready : signal is "xilinx.com:interface:axis:1.0 m21 TREADY";
  attribute X_INTERFACE_INFO of s22_tdata : signal is "xilinx.com:interface:axis:1.0 s22 TDATA";
  attribute X_INTERFACE_MODE of s22_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s22_tdata : signal is "XIL_INTERFACENAME s22, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s22_tvalid : signal is "xilinx.com:interface:axis:1.0 s22 TVALID";
  attribute X_INTERFACE_MODE of s22_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m22_tdata : signal is "xilinx.com:interface:axis:1.0 m22 TDATA";
  attribute X_INTERFACE_MODE of m22_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m22_tdata : signal is "XIL_INTERFACENAME m22, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m22_tvalid : signal is "xilinx.com:interface:axis:1.0 m22 TVALID";
  attribute X_INTERFACE_INFO of m22_tready : signal is "xilinx.com:interface:axis:1.0 m22 TREADY";
  attribute X_INTERFACE_INFO of s23_tdata : signal is "xilinx.com:interface:axis:1.0 s23 TDATA";
  attribute X_INTERFACE_MODE of s23_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s23_tdata : signal is "XIL_INTERFACENAME s23, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s23_tvalid : signal is "xilinx.com:interface:axis:1.0 s23 TVALID";
  attribute X_INTERFACE_MODE of s23_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m23_tdata : signal is "xilinx.com:interface:axis:1.0 m23 TDATA";
  attribute X_INTERFACE_MODE of m23_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m23_tdata : signal is "XIL_INTERFACENAME m23, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m23_tvalid : signal is "xilinx.com:interface:axis:1.0 m23 TVALID";
  attribute X_INTERFACE_INFO of m23_tready : signal is "xilinx.com:interface:axis:1.0 m23 TREADY";
  attribute X_INTERFACE_INFO of s30_tdata : signal is "xilinx.com:interface:axis:1.0 s30 TDATA";
  attribute X_INTERFACE_MODE of s30_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s30_tdata : signal is "XIL_INTERFACENAME s30, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s30_tvalid : signal is "xilinx.com:interface:axis:1.0 s30 TVALID";
  attribute X_INTERFACE_MODE of s30_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m30_tdata : signal is "xilinx.com:interface:axis:1.0 m30 TDATA";
  attribute X_INTERFACE_MODE of m30_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m30_tdata : signal is "XIL_INTERFACENAME m30, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m30_tvalid : signal is "xilinx.com:interface:axis:1.0 m30 TVALID";
  attribute X_INTERFACE_INFO of m30_tready : signal is "xilinx.com:interface:axis:1.0 m30 TREADY";
  attribute X_INTERFACE_INFO of s31_tdata : signal is "xilinx.com:interface:axis:1.0 s31 TDATA";
  attribute X_INTERFACE_MODE of s31_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s31_tdata : signal is "XIL_INTERFACENAME s31, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s31_tvalid : signal is "xilinx.com:interface:axis:1.0 s31 TVALID";
  attribute X_INTERFACE_MODE of s31_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m31_tdata : signal is "xilinx.com:interface:axis:1.0 m31 TDATA";
  attribute X_INTERFACE_MODE of m31_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m31_tdata : signal is "XIL_INTERFACENAME m31, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m31_tvalid : signal is "xilinx.com:interface:axis:1.0 m31 TVALID";
  attribute X_INTERFACE_INFO of m31_tready : signal is "xilinx.com:interface:axis:1.0 m31 TREADY";
  attribute X_INTERFACE_INFO of s32_tdata : signal is "xilinx.com:interface:axis:1.0 s32 TDATA";
  attribute X_INTERFACE_MODE of s32_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s32_tdata : signal is "XIL_INTERFACENAME s32, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s32_tvalid : signal is "xilinx.com:interface:axis:1.0 s32 TVALID";
  attribute X_INTERFACE_MODE of s32_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m32_tdata : signal is "xilinx.com:interface:axis:1.0 m32 TDATA";
  attribute X_INTERFACE_MODE of m32_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m32_tdata : signal is "XIL_INTERFACENAME m32, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m32_tvalid : signal is "xilinx.com:interface:axis:1.0 m32 TVALID";
  attribute X_INTERFACE_INFO of m32_tready : signal is "xilinx.com:interface:axis:1.0 m32 TREADY";
  attribute X_INTERFACE_INFO of s33_tdata : signal is "xilinx.com:interface:axis:1.0 s33 TDATA";
  attribute X_INTERFACE_MODE of s33_tdata : signal is "monitor slave";
  attribute X_INTERFACE_PARAMETER of s33_tdata : signal is "XIL_INTERFACENAME s33, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s33_tvalid : signal is "xilinx.com:interface:axis:1.0 s33 TVALID";
  attribute X_INTERFACE_MODE of s33_tvalid : signal is "monitor";
  attribute X_INTERFACE_INFO of m33_tdata : signal is "xilinx.com:interface:axis:1.0 m33 TDATA";
  attribute X_INTERFACE_MODE of m33_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m33_tdata : signal is "XIL_INTERFACENAME m33, TDATA_NUM_BYTES 24, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 409600000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m33_tvalid : signal is "xilinx.com:interface:axis:1.0 m33 TVALID";
  attribute X_INTERFACE_INFO of m33_tready : signal is "xilinx.com:interface:axis:1.0 m33 TREADY";
  attribute X_INTERFACE_INFO of s0_axis_clock : signal is "xilinx.com:signal:clock:1.0 s0_axis_clock CLK";
  attribute X_INTERFACE_MODE of s0_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s0_axis_clock : signal is "XIL_INTERFACENAME s0_axis_clock, ASSOCIATED_BUSIF s00:m00:s01:m01:s02:m02:s03:m03, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s0_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 s0_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of s0_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s0_div2_axis_clock : signal is "XIL_INTERFACENAME s0_div2_axis_clock, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s1_axis_clock : signal is "xilinx.com:signal:clock:1.0 s1_axis_clock CLK";
  attribute X_INTERFACE_MODE of s1_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s1_axis_clock : signal is "XIL_INTERFACENAME s1_axis_clock, ASSOCIATED_BUSIF s10:m10:s11:m11:s12:m12:s13:m13, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s1_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 s1_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of s1_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s1_div2_axis_clock : signal is "XIL_INTERFACENAME s1_div2_axis_clock, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s2_axis_clock : signal is "xilinx.com:signal:clock:1.0 s2_axis_clock CLK";
  attribute X_INTERFACE_MODE of s2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s2_axis_clock : signal is "XIL_INTERFACENAME s2_axis_clock, ASSOCIATED_BUSIF s20:m20:s21:m21:s22:m22:s23:m23, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s2_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 s2_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of s2_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s2_div2_axis_clock : signal is "XIL_INTERFACENAME s2_div2_axis_clock, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s3_axis_clock : signal is "xilinx.com:signal:clock:1.0 s3_axis_clock CLK";
  attribute X_INTERFACE_MODE of s3_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s3_axis_clock : signal is "XIL_INTERFACENAME s3_axis_clock, ASSOCIATED_BUSIF s30:m30:s31:m31:s32:m32:s33:m33, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s3_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 s3_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of s3_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s3_div2_axis_clock : signal is "XIL_INTERFACENAME s3_div2_axis_clock, FREQ_HZ 409600000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_adc3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_aclk : signal is "xilinx.com:signal:clock:1.0 s_axi_aclk CLK";
  attribute X_INTERFACE_MODE of s_axi_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_aclk : signal is "XIL_INTERFACENAME s_axi_aclk, ASSOCIATED_BUSIF s_axi, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ 57500000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_s_axi_aclk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 s_axi_aresetn RST";
  attribute X_INTERFACE_MODE of s_axi_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_aresetn : signal is "XIL_INTERFACENAME s_axi_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "exdes_rfadc_data_bram_capture,Vivado 2025.1";
begin
end;
