# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps/ps.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps || ORIG_REF_NAME==ps} -quiet] -quiet

# IP: bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: c:/radio-zcu208/vivado/adc/adc.gen/sources_1/bd/ps/ps_ooc.xdc
