-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
-- Date        : Thu May 22 09:21:34 2025
-- Host        : xcosswbld25 running 64-bit Ubuntu 22.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /scratch/rfrefdesigns_2025.1_0522_1_ZCU208/trunk/HW/48_trdPllOnddr_dacddr_adcmts_ex/rfip_ex/rfip_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_PS_AXI_interconnect_0_0/rfdc_ex_PS_AXI_interconnect_0_0_stub.vhdl
-- Design      : rfdc_ex_PS_AXI_interconnect_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu48dr-fsvg1517-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity rfdc_ex_PS_AXI_interconnect_0_0 is
  Port ( 
    aclk : in STD_LOGIC;
    aresetn : in STD_LOGIC;
    S00_AXI_awid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_awaddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    S00_AXI_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    S00_AXI_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_awlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    S00_AXI_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S00_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_awqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S00_AXI_awuser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_awvalid : in STD_LOGIC;
    S00_AXI_awready : out STD_LOGIC;
    S00_AXI_wdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    S00_AXI_wstrb : in STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_wlast : in STD_LOGIC;
    S00_AXI_wvalid : in STD_LOGIC;
    S00_AXI_wready : out STD_LOGIC;
    S00_AXI_bid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_bvalid : out STD_LOGIC;
    S00_AXI_bready : in STD_LOGIC;
    S00_AXI_arid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_araddr : in STD_LOGIC_VECTOR ( 39 downto 0 );
    S00_AXI_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    S00_AXI_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_arlock : in STD_LOGIC_VECTOR ( 0 to 0 );
    S00_AXI_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S00_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_arqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S00_AXI_aruser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_arvalid : in STD_LOGIC;
    S00_AXI_arready : out STD_LOGIC;
    S00_AXI_rid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    S00_AXI_rdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    S00_AXI_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_rlast : out STD_LOGIC;
    S00_AXI_rvalid : out STD_LOGIC;
    S00_AXI_rready : in STD_LOGIC;
    M00_AXI_awid : out STD_LOGIC;
    M00_AXI_awaddr : out STD_LOGIC;
    M00_AXI_awlen : out STD_LOGIC;
    M00_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_awlock : out STD_LOGIC;
    M00_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_awuser : out STD_LOGIC;
    M00_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_wid : out STD_LOGIC;
    M00_AXI_wdata : out STD_LOGIC;
    M00_AXI_wstrb : out STD_LOGIC;
    M00_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_wuser : out STD_LOGIC;
    M00_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_bid : in STD_LOGIC;
    M00_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_buser : in STD_LOGIC;
    M00_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_arid : out STD_LOGIC;
    M00_AXI_araddr : out STD_LOGIC;
    M00_AXI_arlen : out STD_LOGIC;
    M00_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_arlock : out STD_LOGIC;
    M00_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_aruser : out STD_LOGIC;
    M00_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_rid : in STD_LOGIC;
    M00_AXI_rdata : in STD_LOGIC;
    M00_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_ruser : in STD_LOGIC;
    M00_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M00_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M01_AXI_awaddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M01_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M01_AXI_awvalid : out STD_LOGIC;
    M01_AXI_awready : in STD_LOGIC;
    M01_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M01_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M01_AXI_wvalid : out STD_LOGIC;
    M01_AXI_wready : in STD_LOGIC;
    M01_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M01_AXI_bvalid : in STD_LOGIC;
    M01_AXI_bready : out STD_LOGIC;
    M01_AXI_araddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M01_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M01_AXI_arvalid : out STD_LOGIC;
    M01_AXI_arready : in STD_LOGIC;
    M01_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M01_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M01_AXI_rvalid : in STD_LOGIC;
    M01_AXI_rready : out STD_LOGIC;
    M02_AXI_awaddr : out STD_LOGIC_VECTOR ( 9 downto 0 );
    M02_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M02_AXI_awvalid : out STD_LOGIC;
    M02_AXI_awready : in STD_LOGIC;
    M02_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M02_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M02_AXI_wvalid : out STD_LOGIC;
    M02_AXI_wready : in STD_LOGIC;
    M02_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M02_AXI_bvalid : in STD_LOGIC;
    M02_AXI_bready : out STD_LOGIC;
    M02_AXI_araddr : out STD_LOGIC_VECTOR ( 9 downto 0 );
    M02_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M02_AXI_arvalid : out STD_LOGIC;
    M02_AXI_arready : in STD_LOGIC;
    M02_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M02_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M02_AXI_rvalid : in STD_LOGIC;
    M02_AXI_rready : out STD_LOGIC;
    M03_AXI_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    M03_AXI_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M03_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_awlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    M03_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_awuser : out STD_LOGIC_VECTOR ( 129 downto 0 );
    M03_AXI_awvalid : out STD_LOGIC;
    M03_AXI_awready : in STD_LOGIC;
    M03_AXI_wdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    M03_AXI_wstrb : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M03_AXI_wlast : out STD_LOGIC;
    M03_AXI_wuser : out STD_LOGIC_VECTOR ( 13 downto 0 );
    M03_AXI_wvalid : out STD_LOGIC;
    M03_AXI_wready : in STD_LOGIC;
    M03_AXI_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_buser : in STD_LOGIC_VECTOR ( 113 downto 0 );
    M03_AXI_bvalid : in STD_LOGIC;
    M03_AXI_bready : out STD_LOGIC;
    M03_AXI_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    M03_AXI_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M03_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_arlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    M03_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_aruser : out STD_LOGIC_VECTOR ( 129 downto 0 );
    M03_AXI_arvalid : out STD_LOGIC;
    M03_AXI_arready : in STD_LOGIC;
    M03_AXI_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_rdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    M03_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_rlast : in STD_LOGIC;
    M03_AXI_ruser : in STD_LOGIC_VECTOR ( 13 downto 0 );
    M03_AXI_rvalid : in STD_LOGIC;
    M03_AXI_rready : out STD_LOGIC;
    M04_AXI_awaddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M04_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M04_AXI_awvalid : out STD_LOGIC;
    M04_AXI_awready : in STD_LOGIC;
    M04_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M04_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M04_AXI_wvalid : out STD_LOGIC;
    M04_AXI_wready : in STD_LOGIC;
    M04_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M04_AXI_bvalid : in STD_LOGIC;
    M04_AXI_bready : out STD_LOGIC;
    M04_AXI_araddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M04_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M04_AXI_arvalid : out STD_LOGIC;
    M04_AXI_arready : in STD_LOGIC;
    M04_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M04_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M04_AXI_rvalid : in STD_LOGIC;
    M04_AXI_rready : out STD_LOGIC;
    M05_AXI_awaddr : out STD_LOGIC_VECTOR ( 9 downto 0 );
    M05_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_awvalid : out STD_LOGIC;
    M05_AXI_awready : in STD_LOGIC;
    M05_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M05_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_wvalid : out STD_LOGIC;
    M05_AXI_wready : in STD_LOGIC;
    M05_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_bvalid : in STD_LOGIC;
    M05_AXI_bready : out STD_LOGIC;
    M05_AXI_araddr : out STD_LOGIC_VECTOR ( 9 downto 0 );
    M05_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_arvalid : out STD_LOGIC;
    M05_AXI_arready : in STD_LOGIC;
    M05_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M05_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_rvalid : in STD_LOGIC;
    M05_AXI_rready : out STD_LOGIC;
    M06_AXI_awaddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M06_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_awvalid : out STD_LOGIC;
    M06_AXI_awready : in STD_LOGIC;
    M06_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M06_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_wvalid : out STD_LOGIC;
    M06_AXI_wready : in STD_LOGIC;
    M06_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_bvalid : in STD_LOGIC;
    M06_AXI_bready : out STD_LOGIC;
    M06_AXI_araddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M06_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_arvalid : out STD_LOGIC;
    M06_AXI_arready : in STD_LOGIC;
    M06_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M06_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_rvalid : in STD_LOGIC;
    M06_AXI_rready : out STD_LOGIC;
    M07_AXI_awaddr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_awvalid : out STD_LOGIC;
    M07_AXI_awready : in STD_LOGIC;
    M07_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M07_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_wvalid : out STD_LOGIC;
    M07_AXI_wready : in STD_LOGIC;
    M07_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_bvalid : in STD_LOGIC;
    M07_AXI_bready : out STD_LOGIC;
    M07_AXI_araddr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_arvalid : out STD_LOGIC;
    M07_AXI_arready : in STD_LOGIC;
    M07_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M07_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_rvalid : in STD_LOGIC;
    M07_AXI_rready : out STD_LOGIC;
    M08_AXI_awaddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M08_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M08_AXI_awvalid : out STD_LOGIC;
    M08_AXI_awready : in STD_LOGIC;
    M08_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M08_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M08_AXI_wvalid : out STD_LOGIC;
    M08_AXI_wready : in STD_LOGIC;
    M08_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M08_AXI_bvalid : in STD_LOGIC;
    M08_AXI_bready : out STD_LOGIC;
    M08_AXI_araddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M08_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M08_AXI_arvalid : out STD_LOGIC;
    M08_AXI_arready : in STD_LOGIC;
    M08_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M08_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M08_AXI_rvalid : in STD_LOGIC;
    M08_AXI_rready : out STD_LOGIC;
    M09_AXI_awid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    M09_AXI_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M09_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_awlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awuser : out STD_LOGIC_VECTOR ( 129 downto 0 );
    M09_AXI_awvalid : out STD_LOGIC;
    M09_AXI_awready : in STD_LOGIC;
    M09_AXI_wdata : out STD_LOGIC_VECTOR ( 511 downto 0 );
    M09_AXI_wstrb : out STD_LOGIC_VECTOR ( 63 downto 0 );
    M09_AXI_wlast : out STD_LOGIC;
    M09_AXI_wuser : out STD_LOGIC_VECTOR ( 13 downto 0 );
    M09_AXI_wvalid : out STD_LOGIC;
    M09_AXI_wready : in STD_LOGIC;
    M09_AXI_bid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_buser : in STD_LOGIC_VECTOR ( 113 downto 0 );
    M09_AXI_bvalid : in STD_LOGIC;
    M09_AXI_bready : out STD_LOGIC;
    M09_AXI_arid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    M09_AXI_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M09_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_arlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_aruser : out STD_LOGIC_VECTOR ( 129 downto 0 );
    M09_AXI_arvalid : out STD_LOGIC;
    M09_AXI_arready : in STD_LOGIC;
    M09_AXI_rid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_rdata : in STD_LOGIC_VECTOR ( 511 downto 0 );
    M09_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_rlast : in STD_LOGIC;
    M09_AXI_ruser : in STD_LOGIC_VECTOR ( 13 downto 0 );
    M09_AXI_rvalid : in STD_LOGIC;
    M09_AXI_rready : out STD_LOGIC;
    M10_AXI_awaddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M10_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_awvalid : out STD_LOGIC;
    M10_AXI_awready : in STD_LOGIC;
    M10_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M10_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_wvalid : out STD_LOGIC;
    M10_AXI_wready : in STD_LOGIC;
    M10_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_bvalid : in STD_LOGIC;
    M10_AXI_bready : out STD_LOGIC;
    M10_AXI_araddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M10_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_arvalid : out STD_LOGIC;
    M10_AXI_arready : in STD_LOGIC;
    M10_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M10_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_rvalid : in STD_LOGIC;
    M10_AXI_rready : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of rfdc_ex_PS_AXI_interconnect_0_0 : entity is "rfdc_ex_PS_AXI_interconnect_0_0,bd_cc90,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of rfdc_ex_PS_AXI_interconnect_0_0 : entity is "rfdc_ex_PS_AXI_interconnect_0_0,bd_cc90,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=smartconnect,x_ipVersion=1.0,x_ipCoreRevision=27,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of rfdc_ex_PS_AXI_interconnect_0_0 : entity is "yes";
end rfdc_ex_PS_AXI_interconnect_0_0;

architecture stub of rfdc_ex_PS_AXI_interconnect_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "aclk,aresetn,S00_AXI_awid[15:0],S00_AXI_awaddr[39:0],S00_AXI_awlen[7:0],S00_AXI_awsize[2:0],S00_AXI_awburst[1:0],S00_AXI_awlock[0:0],S00_AXI_awcache[3:0],S00_AXI_awprot[2:0],S00_AXI_awqos[3:0],S00_AXI_awuser[15:0],S00_AXI_awvalid,S00_AXI_awready,S00_AXI_wdata[127:0],S00_AXI_wstrb[15:0],S00_AXI_wlast,S00_AXI_wvalid,S00_AXI_wready,S00_AXI_bid[15:0],S00_AXI_bresp[1:0],S00_AXI_bvalid,S00_AXI_bready,S00_AXI_arid[15:0],S00_AXI_araddr[39:0],S00_AXI_arlen[7:0],S00_AXI_arsize[2:0],S00_AXI_arburst[1:0],S00_AXI_arlock[0:0],S00_AXI_arcache[3:0],S00_AXI_arprot[2:0],S00_AXI_arqos[3:0],S00_AXI_aruser[15:0],S00_AXI_arvalid,S00_AXI_arready,S00_AXI_rid[15:0],S00_AXI_rdata[127:0],S00_AXI_rresp[1:0],S00_AXI_rlast,S00_AXI_rvalid,S00_AXI_rready,M00_AXI_awid,M00_AXI_awaddr,M00_AXI_awlen,M00_AXI_awsize[2:0],M00_AXI_awburst[1:0],M00_AXI_awlock,M00_AXI_awcache[3:0],M00_AXI_awprot[2:0],M00_AXI_awregion[3:0],M00_AXI_awqos[3:0],M00_AXI_awuser,M00_AXI_awvalid[0:0],M00_AXI_awready[0:0],M00_AXI_wid,M00_AXI_wdata,M00_AXI_wstrb,M00_AXI_wlast[0:0],M00_AXI_wuser,M00_AXI_wvalid[0:0],M00_AXI_wready[0:0],M00_AXI_bid,M00_AXI_bresp[1:0],M00_AXI_buser,M00_AXI_bvalid[0:0],M00_AXI_bready[0:0],M00_AXI_arid,M00_AXI_araddr,M00_AXI_arlen,M00_AXI_arsize[2:0],M00_AXI_arburst[1:0],M00_AXI_arlock,M00_AXI_arcache[3:0],M00_AXI_arprot[2:0],M00_AXI_arregion[3:0],M00_AXI_arqos[3:0],M00_AXI_aruser,M00_AXI_arvalid[0:0],M00_AXI_arready[0:0],M00_AXI_rid,M00_AXI_rdata,M00_AXI_rresp[1:0],M00_AXI_rlast[0:0],M00_AXI_ruser,M00_AXI_rvalid[0:0],M00_AXI_rready[0:0],M01_AXI_awaddr[8:0],M01_AXI_awprot[2:0],M01_AXI_awvalid,M01_AXI_awready,M01_AXI_wdata[31:0],M01_AXI_wstrb[3:0],M01_AXI_wvalid,M01_AXI_wready,M01_AXI_bresp[1:0],M01_AXI_bvalid,M01_AXI_bready,M01_AXI_araddr[8:0],M01_AXI_arprot[2:0],M01_AXI_arvalid,M01_AXI_arready,M01_AXI_rdata[31:0],M01_AXI_rresp[1:0],M01_AXI_rvalid,M01_AXI_rready,M02_AXI_awaddr[9:0],M02_AXI_awprot[2:0],M02_AXI_awvalid,M02_AXI_awready,M02_AXI_wdata[31:0],M02_AXI_wstrb[3:0],M02_AXI_wvalid,M02_AXI_wready,M02_AXI_bresp[1:0],M02_AXI_bvalid,M02_AXI_bready,M02_AXI_araddr[9:0],M02_AXI_arprot[2:0],M02_AXI_arvalid,M02_AXI_arready,M02_AXI_rdata[31:0],M02_AXI_rresp[1:0],M02_AXI_rvalid,M02_AXI_rready,M03_AXI_awid[3:0],M03_AXI_awaddr[39:0],M03_AXI_awlen[7:0],M03_AXI_awsize[2:0],M03_AXI_awburst[1:0],M03_AXI_awlock[0:0],M03_AXI_awcache[3:0],M03_AXI_awprot[2:0],M03_AXI_awqos[3:0],M03_AXI_awuser[129:0],M03_AXI_awvalid,M03_AXI_awready,M03_AXI_wdata[255:0],M03_AXI_wstrb[31:0],M03_AXI_wlast,M03_AXI_wuser[13:0],M03_AXI_wvalid,M03_AXI_wready,M03_AXI_bid[3:0],M03_AXI_bresp[1:0],M03_AXI_buser[113:0],M03_AXI_bvalid,M03_AXI_bready,M03_AXI_arid[3:0],M03_AXI_araddr[39:0],M03_AXI_arlen[7:0],M03_AXI_arsize[2:0],M03_AXI_arburst[1:0],M03_AXI_arlock[0:0],M03_AXI_arcache[3:0],M03_AXI_arprot[2:0],M03_AXI_arqos[3:0],M03_AXI_aruser[129:0],M03_AXI_arvalid,M03_AXI_arready,M03_AXI_rid[3:0],M03_AXI_rdata[255:0],M03_AXI_rresp[1:0],M03_AXI_rlast,M03_AXI_ruser[13:0],M03_AXI_rvalid,M03_AXI_rready,M04_AXI_awaddr[8:0],M04_AXI_awprot[2:0],M04_AXI_awvalid,M04_AXI_awready,M04_AXI_wdata[31:0],M04_AXI_wstrb[3:0],M04_AXI_wvalid,M04_AXI_wready,M04_AXI_bresp[1:0],M04_AXI_bvalid,M04_AXI_bready,M04_AXI_araddr[8:0],M04_AXI_arprot[2:0],M04_AXI_arvalid,M04_AXI_arready,M04_AXI_rdata[31:0],M04_AXI_rresp[1:0],M04_AXI_rvalid,M04_AXI_rready,M05_AXI_awaddr[9:0],M05_AXI_awprot[2:0],M05_AXI_awvalid,M05_AXI_awready,M05_AXI_wdata[31:0],M05_AXI_wstrb[3:0],M05_AXI_wvalid,M05_AXI_wready,M05_AXI_bresp[1:0],M05_AXI_bvalid,M05_AXI_bready,M05_AXI_araddr[9:0],M05_AXI_arprot[2:0],M05_AXI_arvalid,M05_AXI_arready,M05_AXI_rdata[31:0],M05_AXI_rresp[1:0],M05_AXI_rvalid,M05_AXI_rready,M06_AXI_awaddr[6:0],M06_AXI_awprot[2:0],M06_AXI_awvalid,M06_AXI_awready,M06_AXI_wdata[31:0],M06_AXI_wstrb[3:0],M06_AXI_wvalid,M06_AXI_wready,M06_AXI_bresp[1:0],M06_AXI_bvalid,M06_AXI_bready,M06_AXI_araddr[6:0],M06_AXI_arprot[2:0],M06_AXI_arvalid,M06_AXI_arready,M06_AXI_rdata[31:0],M06_AXI_rresp[1:0],M06_AXI_rvalid,M06_AXI_rready,M07_AXI_awaddr[3:0],M07_AXI_awprot[2:0],M07_AXI_awvalid,M07_AXI_awready,M07_AXI_wdata[31:0],M07_AXI_wstrb[3:0],M07_AXI_wvalid,M07_AXI_wready,M07_AXI_bresp[1:0],M07_AXI_bvalid,M07_AXI_bready,M07_AXI_araddr[3:0],M07_AXI_arprot[2:0],M07_AXI_arvalid,M07_AXI_arready,M07_AXI_rdata[31:0],M07_AXI_rresp[1:0],M07_AXI_rvalid,M07_AXI_rready,M08_AXI_awaddr[8:0],M08_AXI_awprot[2:0],M08_AXI_awvalid,M08_AXI_awready,M08_AXI_wdata[31:0],M08_AXI_wstrb[3:0],M08_AXI_wvalid,M08_AXI_wready,M08_AXI_bresp[1:0],M08_AXI_bvalid,M08_AXI_bready,M08_AXI_araddr[8:0],M08_AXI_arprot[2:0],M08_AXI_arvalid,M08_AXI_arready,M08_AXI_rdata[31:0],M08_AXI_rresp[1:0],M08_AXI_rvalid,M08_AXI_rready,M09_AXI_awid[3:0],M09_AXI_awaddr[39:0],M09_AXI_awlen[7:0],M09_AXI_awsize[2:0],M09_AXI_awburst[1:0],M09_AXI_awlock[0:0],M09_AXI_awcache[3:0],M09_AXI_awprot[2:0],M09_AXI_awqos[3:0],M09_AXI_awuser[129:0],M09_AXI_awvalid,M09_AXI_awready,M09_AXI_wdata[511:0],M09_AXI_wstrb[63:0],M09_AXI_wlast,M09_AXI_wuser[13:0],M09_AXI_wvalid,M09_AXI_wready,M09_AXI_bid[3:0],M09_AXI_bresp[1:0],M09_AXI_buser[113:0],M09_AXI_bvalid,M09_AXI_bready,M09_AXI_arid[3:0],M09_AXI_araddr[39:0],M09_AXI_arlen[7:0],M09_AXI_arsize[2:0],M09_AXI_arburst[1:0],M09_AXI_arlock[0:0],M09_AXI_arcache[3:0],M09_AXI_arprot[2:0],M09_AXI_arqos[3:0],M09_AXI_aruser[129:0],M09_AXI_arvalid,M09_AXI_arready,M09_AXI_rid[3:0],M09_AXI_rdata[511:0],M09_AXI_rresp[1:0],M09_AXI_rlast,M09_AXI_ruser[13:0],M09_AXI_rvalid,M09_AXI_rready,M10_AXI_awaddr[8:0],M10_AXI_awprot[2:0],M10_AXI_awvalid,M10_AXI_awready,M10_AXI_wdata[31:0],M10_AXI_wstrb[3:0],M10_AXI_wvalid,M10_AXI_wready,M10_AXI_bresp[1:0],M10_AXI_bvalid,M10_AXI_bready,M10_AXI_araddr[8:0],M10_AXI_arprot[2:0],M10_AXI_arvalid,M10_AXI_arready,M10_AXI_rdata[31:0],M10_AXI_rresp[1:0],M10_AXI_rvalid,M10_AXI_rready";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of aclk : signal is "xilinx.com:signal:clock:1.0 CLK.aclk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of aclk : signal is "XIL_INTERFACENAME CLK.aclk, FREQ_HZ 99999001, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, ASSOCIATED_BUSIF M00_AXI:M01_AXI:M02_AXI:M03_AXI:M04_AXI:M05_AXI:M06_AXI:M07_AXI:M08_AXI:M09_AXI:M10_AXI:S00_AXI, INSERT_VIP 0, ASSOCIATED_CLKEN m_sc_aclken";
  attribute X_INTERFACE_INFO of aresetn : signal is "xilinx.com:signal:reset:1.0 RST.aresetn RST";
  attribute X_INTERFACE_MODE of aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aresetn : signal is "XIL_INTERFACENAME RST.aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S00_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWID";
  attribute X_INTERFACE_MODE of S00_AXI_awid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of S00_AXI_awid : signal is "XIL_INTERFACENAME S00_AXI, DATA_WIDTH 128, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 16, ADDR_WIDTH 40, AWUSER_WIDTH 16, ARUSER_WIDTH 16, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 4, NUM_WRITE_THREADS 4, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S00_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWADDR";
  attribute X_INTERFACE_INFO of S00_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWLEN";
  attribute X_INTERFACE_INFO of S00_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWSIZE";
  attribute X_INTERFACE_INFO of S00_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWBURST";
  attribute X_INTERFACE_INFO of S00_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWLOCK";
  attribute X_INTERFACE_INFO of S00_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWCACHE";
  attribute X_INTERFACE_INFO of S00_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWPROT";
  attribute X_INTERFACE_INFO of S00_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWQOS";
  attribute X_INTERFACE_INFO of S00_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWUSER";
  attribute X_INTERFACE_INFO of S00_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWVALID";
  attribute X_INTERFACE_INFO of S00_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWREADY";
  attribute X_INTERFACE_INFO of S00_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WDATA";
  attribute X_INTERFACE_INFO of S00_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WSTRB";
  attribute X_INTERFACE_INFO of S00_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WLAST";
  attribute X_INTERFACE_INFO of S00_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WVALID";
  attribute X_INTERFACE_INFO of S00_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WREADY";
  attribute X_INTERFACE_INFO of S00_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BID";
  attribute X_INTERFACE_INFO of S00_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BRESP";
  attribute X_INTERFACE_INFO of S00_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BVALID";
  attribute X_INTERFACE_INFO of S00_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BREADY";
  attribute X_INTERFACE_INFO of S00_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARID";
  attribute X_INTERFACE_INFO of S00_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARADDR";
  attribute X_INTERFACE_INFO of S00_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARLEN";
  attribute X_INTERFACE_INFO of S00_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARSIZE";
  attribute X_INTERFACE_INFO of S00_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARBURST";
  attribute X_INTERFACE_INFO of S00_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARLOCK";
  attribute X_INTERFACE_INFO of S00_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARCACHE";
  attribute X_INTERFACE_INFO of S00_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARPROT";
  attribute X_INTERFACE_INFO of S00_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARQOS";
  attribute X_INTERFACE_INFO of S00_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARUSER";
  attribute X_INTERFACE_INFO of S00_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARVALID";
  attribute X_INTERFACE_INFO of S00_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARREADY";
  attribute X_INTERFACE_INFO of S00_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RID";
  attribute X_INTERFACE_INFO of S00_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RDATA";
  attribute X_INTERFACE_INFO of S00_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RRESP";
  attribute X_INTERFACE_INFO of S00_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RLAST";
  attribute X_INTERFACE_INFO of S00_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RVALID";
  attribute X_INTERFACE_INFO of S00_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RREADY";
  attribute X_INTERFACE_INFO of M00_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWID";
  attribute X_INTERFACE_MODE of M00_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M00_AXI_awid : signal is "XIL_INTERFACENAME M00_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M00_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWADDR";
  attribute X_INTERFACE_INFO of M00_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWLEN";
  attribute X_INTERFACE_INFO of M00_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M00_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWBURST";
  attribute X_INTERFACE_INFO of M00_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M00_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M00_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWPROT";
  attribute X_INTERFACE_INFO of M00_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWREGION";
  attribute X_INTERFACE_INFO of M00_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWQOS";
  attribute X_INTERFACE_INFO of M00_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWUSER";
  attribute X_INTERFACE_INFO of M00_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWVALID";
  attribute X_INTERFACE_INFO of M00_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWREADY";
  attribute X_INTERFACE_INFO of M00_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WID";
  attribute X_INTERFACE_INFO of M00_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WDATA";
  attribute X_INTERFACE_INFO of M00_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WSTRB";
  attribute X_INTERFACE_INFO of M00_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WLAST";
  attribute X_INTERFACE_INFO of M00_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WUSER";
  attribute X_INTERFACE_INFO of M00_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WVALID";
  attribute X_INTERFACE_INFO of M00_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WREADY";
  attribute X_INTERFACE_INFO of M00_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BID";
  attribute X_INTERFACE_INFO of M00_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BRESP";
  attribute X_INTERFACE_INFO of M00_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BUSER";
  attribute X_INTERFACE_INFO of M00_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BVALID";
  attribute X_INTERFACE_INFO of M00_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BREADY";
  attribute X_INTERFACE_INFO of M00_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARID";
  attribute X_INTERFACE_INFO of M00_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARADDR";
  attribute X_INTERFACE_INFO of M00_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARLEN";
  attribute X_INTERFACE_INFO of M00_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M00_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARBURST";
  attribute X_INTERFACE_INFO of M00_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M00_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M00_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARPROT";
  attribute X_INTERFACE_INFO of M00_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARREGION";
  attribute X_INTERFACE_INFO of M00_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARQOS";
  attribute X_INTERFACE_INFO of M00_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARUSER";
  attribute X_INTERFACE_INFO of M00_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARVALID";
  attribute X_INTERFACE_INFO of M00_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARREADY";
  attribute X_INTERFACE_INFO of M00_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RID";
  attribute X_INTERFACE_INFO of M00_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RDATA";
  attribute X_INTERFACE_INFO of M00_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RRESP";
  attribute X_INTERFACE_INFO of M00_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RLAST";
  attribute X_INTERFACE_INFO of M00_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RUSER";
  attribute X_INTERFACE_INFO of M00_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RVALID";
  attribute X_INTERFACE_INFO of M00_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RREADY";
  attribute X_INTERFACE_INFO of M01_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWADDR";
  attribute X_INTERFACE_MODE of M01_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M01_AXI_awaddr : signal is "XIL_INTERFACENAME M01_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M01_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWPROT";
  attribute X_INTERFACE_INFO of M01_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWVALID";
  attribute X_INTERFACE_INFO of M01_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWREADY";
  attribute X_INTERFACE_INFO of M01_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WDATA";
  attribute X_INTERFACE_INFO of M01_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WSTRB";
  attribute X_INTERFACE_INFO of M01_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WVALID";
  attribute X_INTERFACE_INFO of M01_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WREADY";
  attribute X_INTERFACE_INFO of M01_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BRESP";
  attribute X_INTERFACE_INFO of M01_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BVALID";
  attribute X_INTERFACE_INFO of M01_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BREADY";
  attribute X_INTERFACE_INFO of M01_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARADDR";
  attribute X_INTERFACE_INFO of M01_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARPROT";
  attribute X_INTERFACE_INFO of M01_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARVALID";
  attribute X_INTERFACE_INFO of M01_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARREADY";
  attribute X_INTERFACE_INFO of M01_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RDATA";
  attribute X_INTERFACE_INFO of M01_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RRESP";
  attribute X_INTERFACE_INFO of M01_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RVALID";
  attribute X_INTERFACE_INFO of M01_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RREADY";
  attribute X_INTERFACE_INFO of M02_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWADDR";
  attribute X_INTERFACE_MODE of M02_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M02_AXI_awaddr : signal is "XIL_INTERFACENAME M02_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 10, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M02_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWPROT";
  attribute X_INTERFACE_INFO of M02_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWVALID";
  attribute X_INTERFACE_INFO of M02_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWREADY";
  attribute X_INTERFACE_INFO of M02_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WDATA";
  attribute X_INTERFACE_INFO of M02_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WSTRB";
  attribute X_INTERFACE_INFO of M02_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WVALID";
  attribute X_INTERFACE_INFO of M02_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WREADY";
  attribute X_INTERFACE_INFO of M02_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BRESP";
  attribute X_INTERFACE_INFO of M02_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BVALID";
  attribute X_INTERFACE_INFO of M02_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BREADY";
  attribute X_INTERFACE_INFO of M02_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARADDR";
  attribute X_INTERFACE_INFO of M02_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARPROT";
  attribute X_INTERFACE_INFO of M02_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARVALID";
  attribute X_INTERFACE_INFO of M02_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARREADY";
  attribute X_INTERFACE_INFO of M02_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RDATA";
  attribute X_INTERFACE_INFO of M02_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RRESP";
  attribute X_INTERFACE_INFO of M02_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RVALID";
  attribute X_INTERFACE_INFO of M02_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RREADY";
  attribute X_INTERFACE_INFO of M03_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWID";
  attribute X_INTERFACE_MODE of M03_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M03_AXI_awid : signal is "XIL_INTERFACENAME M03_AXI, DATA_WIDTH 256, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 4, ADDR_WIDTH 40, AWUSER_WIDTH 130, ARUSER_WIDTH 130, WUSER_WIDTH 14, RUSER_WIDTH 14, BUSER_WIDTH 114, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 128, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M03_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWADDR";
  attribute X_INTERFACE_INFO of M03_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWLEN";
  attribute X_INTERFACE_INFO of M03_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M03_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWBURST";
  attribute X_INTERFACE_INFO of M03_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M03_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M03_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWPROT";
  attribute X_INTERFACE_INFO of M03_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWQOS";
  attribute X_INTERFACE_INFO of M03_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWUSER";
  attribute X_INTERFACE_INFO of M03_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWVALID";
  attribute X_INTERFACE_INFO of M03_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWREADY";
  attribute X_INTERFACE_INFO of M03_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WDATA";
  attribute X_INTERFACE_INFO of M03_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WSTRB";
  attribute X_INTERFACE_INFO of M03_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WLAST";
  attribute X_INTERFACE_INFO of M03_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WUSER";
  attribute X_INTERFACE_INFO of M03_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WVALID";
  attribute X_INTERFACE_INFO of M03_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WREADY";
  attribute X_INTERFACE_INFO of M03_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BID";
  attribute X_INTERFACE_INFO of M03_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BRESP";
  attribute X_INTERFACE_INFO of M03_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BUSER";
  attribute X_INTERFACE_INFO of M03_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BVALID";
  attribute X_INTERFACE_INFO of M03_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BREADY";
  attribute X_INTERFACE_INFO of M03_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARID";
  attribute X_INTERFACE_INFO of M03_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARADDR";
  attribute X_INTERFACE_INFO of M03_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARLEN";
  attribute X_INTERFACE_INFO of M03_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M03_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARBURST";
  attribute X_INTERFACE_INFO of M03_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M03_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M03_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARPROT";
  attribute X_INTERFACE_INFO of M03_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARQOS";
  attribute X_INTERFACE_INFO of M03_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARUSER";
  attribute X_INTERFACE_INFO of M03_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARVALID";
  attribute X_INTERFACE_INFO of M03_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARREADY";
  attribute X_INTERFACE_INFO of M03_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RID";
  attribute X_INTERFACE_INFO of M03_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RDATA";
  attribute X_INTERFACE_INFO of M03_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RRESP";
  attribute X_INTERFACE_INFO of M03_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RLAST";
  attribute X_INTERFACE_INFO of M03_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RUSER";
  attribute X_INTERFACE_INFO of M03_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RVALID";
  attribute X_INTERFACE_INFO of M03_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RREADY";
  attribute X_INTERFACE_INFO of M04_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWADDR";
  attribute X_INTERFACE_MODE of M04_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M04_AXI_awaddr : signal is "XIL_INTERFACENAME M04_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M04_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWPROT";
  attribute X_INTERFACE_INFO of M04_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWVALID";
  attribute X_INTERFACE_INFO of M04_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWREADY";
  attribute X_INTERFACE_INFO of M04_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WDATA";
  attribute X_INTERFACE_INFO of M04_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WSTRB";
  attribute X_INTERFACE_INFO of M04_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WVALID";
  attribute X_INTERFACE_INFO of M04_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WREADY";
  attribute X_INTERFACE_INFO of M04_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BRESP";
  attribute X_INTERFACE_INFO of M04_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BVALID";
  attribute X_INTERFACE_INFO of M04_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BREADY";
  attribute X_INTERFACE_INFO of M04_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARADDR";
  attribute X_INTERFACE_INFO of M04_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARPROT";
  attribute X_INTERFACE_INFO of M04_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARVALID";
  attribute X_INTERFACE_INFO of M04_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARREADY";
  attribute X_INTERFACE_INFO of M04_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RDATA";
  attribute X_INTERFACE_INFO of M04_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RRESP";
  attribute X_INTERFACE_INFO of M04_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RVALID";
  attribute X_INTERFACE_INFO of M04_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RREADY";
  attribute X_INTERFACE_INFO of M05_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWADDR";
  attribute X_INTERFACE_MODE of M05_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M05_AXI_awaddr : signal is "XIL_INTERFACENAME M05_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 10, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M05_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWPROT";
  attribute X_INTERFACE_INFO of M05_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWVALID";
  attribute X_INTERFACE_INFO of M05_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWREADY";
  attribute X_INTERFACE_INFO of M05_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WDATA";
  attribute X_INTERFACE_INFO of M05_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WSTRB";
  attribute X_INTERFACE_INFO of M05_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WVALID";
  attribute X_INTERFACE_INFO of M05_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WREADY";
  attribute X_INTERFACE_INFO of M05_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BRESP";
  attribute X_INTERFACE_INFO of M05_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BVALID";
  attribute X_INTERFACE_INFO of M05_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BREADY";
  attribute X_INTERFACE_INFO of M05_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARADDR";
  attribute X_INTERFACE_INFO of M05_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARPROT";
  attribute X_INTERFACE_INFO of M05_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARVALID";
  attribute X_INTERFACE_INFO of M05_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARREADY";
  attribute X_INTERFACE_INFO of M05_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RDATA";
  attribute X_INTERFACE_INFO of M05_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RRESP";
  attribute X_INTERFACE_INFO of M05_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RVALID";
  attribute X_INTERFACE_INFO of M05_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RREADY";
  attribute X_INTERFACE_INFO of M06_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWADDR";
  attribute X_INTERFACE_MODE of M06_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M06_AXI_awaddr : signal is "XIL_INTERFACENAME M06_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 7, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M06_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWPROT";
  attribute X_INTERFACE_INFO of M06_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWVALID";
  attribute X_INTERFACE_INFO of M06_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWREADY";
  attribute X_INTERFACE_INFO of M06_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WDATA";
  attribute X_INTERFACE_INFO of M06_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WSTRB";
  attribute X_INTERFACE_INFO of M06_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WVALID";
  attribute X_INTERFACE_INFO of M06_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WREADY";
  attribute X_INTERFACE_INFO of M06_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BRESP";
  attribute X_INTERFACE_INFO of M06_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BVALID";
  attribute X_INTERFACE_INFO of M06_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BREADY";
  attribute X_INTERFACE_INFO of M06_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARADDR";
  attribute X_INTERFACE_INFO of M06_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARPROT";
  attribute X_INTERFACE_INFO of M06_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARVALID";
  attribute X_INTERFACE_INFO of M06_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARREADY";
  attribute X_INTERFACE_INFO of M06_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RDATA";
  attribute X_INTERFACE_INFO of M06_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RRESP";
  attribute X_INTERFACE_INFO of M06_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RVALID";
  attribute X_INTERFACE_INFO of M06_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RREADY";
  attribute X_INTERFACE_INFO of M07_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWADDR";
  attribute X_INTERFACE_MODE of M07_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M07_AXI_awaddr : signal is "XIL_INTERFACENAME M07_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 4, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M07_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWPROT";
  attribute X_INTERFACE_INFO of M07_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWVALID";
  attribute X_INTERFACE_INFO of M07_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWREADY";
  attribute X_INTERFACE_INFO of M07_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WDATA";
  attribute X_INTERFACE_INFO of M07_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WSTRB";
  attribute X_INTERFACE_INFO of M07_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WVALID";
  attribute X_INTERFACE_INFO of M07_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WREADY";
  attribute X_INTERFACE_INFO of M07_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BRESP";
  attribute X_INTERFACE_INFO of M07_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BVALID";
  attribute X_INTERFACE_INFO of M07_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BREADY";
  attribute X_INTERFACE_INFO of M07_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARADDR";
  attribute X_INTERFACE_INFO of M07_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARPROT";
  attribute X_INTERFACE_INFO of M07_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARVALID";
  attribute X_INTERFACE_INFO of M07_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARREADY";
  attribute X_INTERFACE_INFO of M07_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RDATA";
  attribute X_INTERFACE_INFO of M07_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RRESP";
  attribute X_INTERFACE_INFO of M07_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RVALID";
  attribute X_INTERFACE_INFO of M07_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RREADY";
  attribute X_INTERFACE_INFO of M08_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWADDR";
  attribute X_INTERFACE_MODE of M08_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M08_AXI_awaddr : signal is "XIL_INTERFACENAME M08_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M08_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWPROT";
  attribute X_INTERFACE_INFO of M08_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWVALID";
  attribute X_INTERFACE_INFO of M08_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWREADY";
  attribute X_INTERFACE_INFO of M08_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WDATA";
  attribute X_INTERFACE_INFO of M08_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WSTRB";
  attribute X_INTERFACE_INFO of M08_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WVALID";
  attribute X_INTERFACE_INFO of M08_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WREADY";
  attribute X_INTERFACE_INFO of M08_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BRESP";
  attribute X_INTERFACE_INFO of M08_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BVALID";
  attribute X_INTERFACE_INFO of M08_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BREADY";
  attribute X_INTERFACE_INFO of M08_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARADDR";
  attribute X_INTERFACE_INFO of M08_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARPROT";
  attribute X_INTERFACE_INFO of M08_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARVALID";
  attribute X_INTERFACE_INFO of M08_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARREADY";
  attribute X_INTERFACE_INFO of M08_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RDATA";
  attribute X_INTERFACE_INFO of M08_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RRESP";
  attribute X_INTERFACE_INFO of M08_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RVALID";
  attribute X_INTERFACE_INFO of M08_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RREADY";
  attribute X_INTERFACE_INFO of M09_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWID";
  attribute X_INTERFACE_MODE of M09_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M09_AXI_awid : signal is "XIL_INTERFACENAME M09_AXI, DATA_WIDTH 512, PROTOCOL AXI4, FREQ_HZ 99999001, ID_WIDTH 4, ADDR_WIDTH 40, AWUSER_WIDTH 130, ARUSER_WIDTH 130, WUSER_WIDTH 14, RUSER_WIDTH 14, BUSER_WIDTH 114, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 64, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M09_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWADDR";
  attribute X_INTERFACE_INFO of M09_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWLEN";
  attribute X_INTERFACE_INFO of M09_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M09_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWBURST";
  attribute X_INTERFACE_INFO of M09_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M09_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M09_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWPROT";
  attribute X_INTERFACE_INFO of M09_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWQOS";
  attribute X_INTERFACE_INFO of M09_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWUSER";
  attribute X_INTERFACE_INFO of M09_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWVALID";
  attribute X_INTERFACE_INFO of M09_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWREADY";
  attribute X_INTERFACE_INFO of M09_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WDATA";
  attribute X_INTERFACE_INFO of M09_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WSTRB";
  attribute X_INTERFACE_INFO of M09_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WLAST";
  attribute X_INTERFACE_INFO of M09_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WUSER";
  attribute X_INTERFACE_INFO of M09_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WVALID";
  attribute X_INTERFACE_INFO of M09_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WREADY";
  attribute X_INTERFACE_INFO of M09_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BID";
  attribute X_INTERFACE_INFO of M09_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BRESP";
  attribute X_INTERFACE_INFO of M09_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BUSER";
  attribute X_INTERFACE_INFO of M09_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BVALID";
  attribute X_INTERFACE_INFO of M09_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BREADY";
  attribute X_INTERFACE_INFO of M09_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARID";
  attribute X_INTERFACE_INFO of M09_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARADDR";
  attribute X_INTERFACE_INFO of M09_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARLEN";
  attribute X_INTERFACE_INFO of M09_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M09_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARBURST";
  attribute X_INTERFACE_INFO of M09_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M09_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M09_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARPROT";
  attribute X_INTERFACE_INFO of M09_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARQOS";
  attribute X_INTERFACE_INFO of M09_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARUSER";
  attribute X_INTERFACE_INFO of M09_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARVALID";
  attribute X_INTERFACE_INFO of M09_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARREADY";
  attribute X_INTERFACE_INFO of M09_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RID";
  attribute X_INTERFACE_INFO of M09_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RDATA";
  attribute X_INTERFACE_INFO of M09_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RRESP";
  attribute X_INTERFACE_INFO of M09_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RLAST";
  attribute X_INTERFACE_INFO of M09_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RUSER";
  attribute X_INTERFACE_INFO of M09_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RVALID";
  attribute X_INTERFACE_INFO of M09_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RREADY";
  attribute X_INTERFACE_INFO of M10_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWADDR";
  attribute X_INTERFACE_MODE of M10_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M10_AXI_awaddr : signal is "XIL_INTERFACENAME M10_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 99999001, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_zynq_ps_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M10_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWPROT";
  attribute X_INTERFACE_INFO of M10_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWVALID";
  attribute X_INTERFACE_INFO of M10_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWREADY";
  attribute X_INTERFACE_INFO of M10_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WDATA";
  attribute X_INTERFACE_INFO of M10_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WSTRB";
  attribute X_INTERFACE_INFO of M10_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WVALID";
  attribute X_INTERFACE_INFO of M10_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WREADY";
  attribute X_INTERFACE_INFO of M10_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BRESP";
  attribute X_INTERFACE_INFO of M10_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BVALID";
  attribute X_INTERFACE_INFO of M10_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BREADY";
  attribute X_INTERFACE_INFO of M10_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARADDR";
  attribute X_INTERFACE_INFO of M10_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARPROT";
  attribute X_INTERFACE_INFO of M10_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARVALID";
  attribute X_INTERFACE_INFO of M10_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARREADY";
  attribute X_INTERFACE_INFO of M10_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RDATA";
  attribute X_INTERFACE_INFO of M10_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RRESP";
  attribute X_INTERFACE_INFO of M10_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RVALID";
  attribute X_INTERFACE_INFO of M10_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RREADY";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "bd_cc90,Vivado 2025.1";
begin
end;
