# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/radio-zcu208/vivado/adc/adc.srcs/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ps_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/radio-zcu208/vivado/adc/adc.gen/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/radio-zcu208/vivado/adc/adc.gen/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/radio-zcu208/vivado/adc/adc.srcs/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ps_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/radio-zcu208/vivado/adc/adc.gen/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/radio-zcu208/vivado/adc/adc.gen/sources_1/bd/ps/ip/ps_zynq_ultra_ps_e_0_0/ps_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
