[config_bsp]
deploy_dir_image = .
image_link_name = petalinux-image-minimal-xlnx-zynqmp-zcu208-reva
image_name = petalinux-image-minimal-xlnx-zynqmp-zcu208-reva-20250911185209
kernel_imagetype = Image
machine = xlnx-zynqmp-zcu208-reva
qb_cmdline_ip_slirp = ip=dhcp
qb_cmdline_ip_tap = ip=192.168.7.@CLIENT@::192.168.7.@GATEWAY@:255.255.255.0::eth0:off:8.8.8.8 net.ifnames=0
qb_default_fstype = cpio.gz.u-boot
qb_default_kernel = BOOT-xlnx-zynqmp-zcu208-reva.bin
qb_drive_type = /dev/sd
qb_dtb = qemu-hw-devicetrees/multiarch/zcu102-arm.dtb
qb_graphics = 
qb_kernel_cmdline = none
qb_kernel_cmdline_append =  swiotlb=0
qb_machine = -machine arm-generic-fdt
qb_mem = -m 4096
qb_network_device = -net nic -net nic -net nic -net nic,netdev=net0,macaddr=@MAC@
qb_nfsrootfs_extra_opt = 
qb_no_pni = net.ifnames=0
qb_opt_append =   -nodefaults      -global xlnx,zynqmp-boot.cpu-num=0 -global xlnx,zynqmp-boot.use-pmufw=true     -device loader,addr=0xfffc0000,data=0x584c4e5801000000,data-be=true,data-len=8     -device loader,addr=0xfffc0008,data=0x0000000800000000,data-be=true,data-len=8     -device loader,addr=0xfffc0010,data=0x1000000000000000,data-be=true,data-len=8     -device loader,addr=0xffd80048,data=0xfffc0000,data-len=4,attrs-secure=on     -device loader,file=@DEPLOY_DIR_IMAGE@/arm-trusted-firmware.elf,cpu-num=0     -device loader,file=@DEPLOY_DIR_IMAGE@/u-boot.elf     -device loader,file=@DEPLOY_DIR_IMAGE@/system.dtb,addr=0x100000,force-raw=on      -boot mode=5       -pmu-args '     -M microblaze-fdt     -display none     -hw-dtb @DEPLOY_DIR_IMAGE@/qemu-hw-devicetrees/multiarch/zynqmp-pmu.dtb     -kernel @DEPLOY_DIR_IMAGE@/pmu-rom.elf     -device loader,file=@DEPLOY_DIR_IMAGE@/pmu-firmware-xlnx-zynqmp-zcu208-reva.elf     -device loader,addr=0xfd1a0074,data=0x1011003,data-len=4     -device loader,addr=0xfd1a007C,data=0x1010f03,data-len=4     '
qb_rng = 
qb_rootfs = 
qb_rootfs_extra_opt = 
qb_rootfs_opt =  -drive if=sd,index=1,file=@ROOTFS@,format=raw
qb_serial_opt = 
qb_smp = 
qb_system_name = qemu-system-aarch64-multiarch
serial_consoles = 115200;ttyPS0 115200;ttyPS1
staging_bindir_native = ../../../work/x86_64-linux/qemu-helper-native/1.0/recipe-sysroot-native/usr/bin
staging_dir_host = ../../../work/xlnx_zynqmp_zcu208_reva-amd-linux/petalinux-image-minimal/1.0/recipe-sysroot
staging_dir_native = ../../../work/xlnx_zynqmp_zcu208_reva-amd-linux/petalinux-image-minimal/1.0/recipe-sysroot-native
tune_arch = aarch64
uninative_loader = ../../../sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2

