-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (lin64) Build 6140274 Wed May 21 22:58:25 MDT 2025
-- Date        : Thu May 22 09:08:58 2025
-- Host        : xcosswbld25 running 64-bit Ubuntu 22.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /scratch/rfrefdesigns_2025.1_0522_1_ZCU208/trunk/HW/48_trdPllOnddr_dacddr_adcmts_ex/rfip_ex/rfip_ex.gen/sources_1/bd/rfdc_ex/ip/rfdc_ex_dac_source_i_0/rfdc_ex_dac_source_i_0_stub.vhdl
-- Design      : rfdc_ex_dac_source_i_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu48dr-fsvg1517-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity rfdc_ex_dac_source_i_0 is
  Port ( 
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 19 downto 0 );
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awready : out STD_LOGIC;
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wready : out STD_LOGIC;
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bready : in STD_LOGIC;
    s_axi_araddr : in STD_LOGIC_VECTOR ( 19 downto 0 );
    s_axi_arvalid : in STD_LOGIC;
    s_axi_arready : out STD_LOGIC;
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rready : in STD_LOGIC;
    m00_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m00_tvalid : out STD_LOGIC;
    m00_tready : in STD_LOGIC;
    s00_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s00_user_tvalid : in STD_LOGIC;
    s00_user_tready : out STD_LOGIC;
    user_select_00 : in STD_LOGIC;
    m01_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m01_tvalid : out STD_LOGIC;
    m01_tready : in STD_LOGIC;
    s01_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s01_user_tvalid : in STD_LOGIC;
    s01_user_tready : out STD_LOGIC;
    user_select_01 : in STD_LOGIC;
    m02_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m02_tvalid : out STD_LOGIC;
    m02_tready : in STD_LOGIC;
    s02_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s02_user_tvalid : in STD_LOGIC;
    s02_user_tready : out STD_LOGIC;
    user_select_02 : in STD_LOGIC;
    m03_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m03_tvalid : out STD_LOGIC;
    m03_tready : in STD_LOGIC;
    s03_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s03_user_tvalid : in STD_LOGIC;
    s03_user_tready : out STD_LOGIC;
    user_select_03 : in STD_LOGIC;
    m10_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m10_tvalid : out STD_LOGIC;
    m10_tready : in STD_LOGIC;
    s10_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s10_user_tvalid : in STD_LOGIC;
    s10_user_tready : out STD_LOGIC;
    user_select_10 : in STD_LOGIC;
    m11_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m11_tvalid : out STD_LOGIC;
    m11_tready : in STD_LOGIC;
    s11_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s11_user_tvalid : in STD_LOGIC;
    s11_user_tready : out STD_LOGIC;
    user_select_11 : in STD_LOGIC;
    m12_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m12_tvalid : out STD_LOGIC;
    m12_tready : in STD_LOGIC;
    s12_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s12_user_tvalid : in STD_LOGIC;
    s12_user_tready : out STD_LOGIC;
    user_select_12 : in STD_LOGIC;
    m13_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m13_tvalid : out STD_LOGIC;
    m13_tready : in STD_LOGIC;
    s13_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s13_user_tvalid : in STD_LOGIC;
    s13_user_tready : out STD_LOGIC;
    user_select_13 : in STD_LOGIC;
    m20_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m20_tvalid : out STD_LOGIC;
    m20_tready : in STD_LOGIC;
    s20_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s20_user_tvalid : in STD_LOGIC;
    s20_user_tready : out STD_LOGIC;
    user_select_20 : in STD_LOGIC;
    m21_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m21_tvalid : out STD_LOGIC;
    m21_tready : in STD_LOGIC;
    s21_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s21_user_tvalid : in STD_LOGIC;
    s21_user_tready : out STD_LOGIC;
    user_select_21 : in STD_LOGIC;
    m22_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m22_tvalid : out STD_LOGIC;
    m22_tready : in STD_LOGIC;
    s22_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s22_user_tvalid : in STD_LOGIC;
    s22_user_tready : out STD_LOGIC;
    user_select_22 : in STD_LOGIC;
    m23_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m23_tvalid : out STD_LOGIC;
    m23_tready : in STD_LOGIC;
    s23_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s23_user_tvalid : in STD_LOGIC;
    s23_user_tready : out STD_LOGIC;
    user_select_23 : in STD_LOGIC;
    m30_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m30_tvalid : out STD_LOGIC;
    m30_tready : in STD_LOGIC;
    s30_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s30_user_tvalid : in STD_LOGIC;
    s30_user_tready : out STD_LOGIC;
    user_select_30 : in STD_LOGIC;
    m31_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m31_tvalid : out STD_LOGIC;
    m31_tready : in STD_LOGIC;
    s31_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s31_user_tvalid : in STD_LOGIC;
    s31_user_tready : out STD_LOGIC;
    user_select_31 : in STD_LOGIC;
    m32_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m32_tvalid : out STD_LOGIC;
    m32_tready : in STD_LOGIC;
    s32_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s32_user_tvalid : in STD_LOGIC;
    s32_user_tready : out STD_LOGIC;
    user_select_32 : in STD_LOGIC;
    m33_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m33_tvalid : out STD_LOGIC;
    m33_tready : in STD_LOGIC;
    s33_user_tdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    s33_user_tvalid : in STD_LOGIC;
    s33_user_tready : out STD_LOGIC;
    user_select_33 : in STD_LOGIC;
    m0_axis_clock : in STD_LOGIC;
    m0_div2_axis_clock : in STD_LOGIC;
    m1_axis_clock : in STD_LOGIC;
    m1_div2_axis_clock : in STD_LOGIC;
    m2_axis_clock : in STD_LOGIC;
    m2_div2_axis_clock : in STD_LOGIC;
    m3_axis_clock : in STD_LOGIC;
    m3_div2_axis_clock : in STD_LOGIC;
    hw_trigger_0 : in STD_LOGIC;
    hw_trigger_en_0 : in STD_LOGIC;
    hw_trigger_1 : in STD_LOGIC;
    hw_trigger_en_1 : in STD_LOGIC;
    hw_trigger_2 : in STD_LOGIC;
    hw_trigger_en_2 : in STD_LOGIC;
    hw_trigger_3 : in STD_LOGIC;
    hw_trigger_en_3 : in STD_LOGIC;
    s_axi_aclk : in STD_LOGIC;
    s_axi_aresetn : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of rfdc_ex_dac_source_i_0 : entity is "rfdc_ex_dac_source_i_0,exdes_rfdac_data_bram_stim,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of rfdc_ex_dac_source_i_0 : entity is "rfdc_ex_dac_source_i_0,exdes_rfdac_data_bram_stim,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=exdes_rfdac_data_bram_stim,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,mem_size=262144,axi_addr_top=19,use_div2_clk_0=0,use_div2_clk_1=0,use_div2_clk_2=0,use_div2_clk_3=0}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of rfdc_ex_dac_source_i_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of rfdc_ex_dac_source_i_0 : entity is "module_ref";
end rfdc_ex_dac_source_i_0;

architecture stub of rfdc_ex_dac_source_i_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_awaddr[19:0],s_axi_awvalid,s_axi_awready,s_axi_wdata[31:0],s_axi_wvalid,s_axi_wready,s_axi_wstrb[3:0],s_axi_bresp[1:0],s_axi_bvalid,s_axi_bready,s_axi_araddr[19:0],s_axi_arvalid,s_axi_arready,s_axi_rdata[31:0],s_axi_rresp[1:0],s_axi_rvalid,s_axi_rready,m00_tdata[255:0],m00_tvalid,m00_tready,s00_user_tdata[255:0],s00_user_tvalid,s00_user_tready,user_select_00,m01_tdata[255:0],m01_tvalid,m01_tready,s01_user_tdata[255:0],s01_user_tvalid,s01_user_tready,user_select_01,m02_tdata[255:0],m02_tvalid,m02_tready,s02_user_tdata[255:0],s02_user_tvalid,s02_user_tready,user_select_02,m03_tdata[255:0],m03_tvalid,m03_tready,s03_user_tdata[255:0],s03_user_tvalid,s03_user_tready,user_select_03,m10_tdata[255:0],m10_tvalid,m10_tready,s10_user_tdata[255:0],s10_user_tvalid,s10_user_tready,user_select_10,m11_tdata[255:0],m11_tvalid,m11_tready,s11_user_tdata[255:0],s11_user_tvalid,s11_user_tready,user_select_11,m12_tdata[255:0],m12_tvalid,m12_tready,s12_user_tdata[255:0],s12_user_tvalid,s12_user_tready,user_select_12,m13_tdata[255:0],m13_tvalid,m13_tready,s13_user_tdata[255:0],s13_user_tvalid,s13_user_tready,user_select_13,m20_tdata[255:0],m20_tvalid,m20_tready,s20_user_tdata[255:0],s20_user_tvalid,s20_user_tready,user_select_20,m21_tdata[255:0],m21_tvalid,m21_tready,s21_user_tdata[255:0],s21_user_tvalid,s21_user_tready,user_select_21,m22_tdata[255:0],m22_tvalid,m22_tready,s22_user_tdata[255:0],s22_user_tvalid,s22_user_tready,user_select_22,m23_tdata[255:0],m23_tvalid,m23_tready,s23_user_tdata[255:0],s23_user_tvalid,s23_user_tready,user_select_23,m30_tdata[255:0],m30_tvalid,m30_tready,s30_user_tdata[255:0],s30_user_tvalid,s30_user_tready,user_select_30,m31_tdata[255:0],m31_tvalid,m31_tready,s31_user_tdata[255:0],s31_user_tvalid,s31_user_tready,user_select_31,m32_tdata[255:0],m32_tvalid,m32_tready,s32_user_tdata[255:0],s32_user_tvalid,s32_user_tready,user_select_32,m33_tdata[255:0],m33_tvalid,m33_tready,s33_user_tdata[255:0],s33_user_tvalid,s33_user_tready,user_select_33,m0_axis_clock,m0_div2_axis_clock,m1_axis_clock,m1_div2_axis_clock,m2_axis_clock,m2_div2_axis_clock,m3_axis_clock,m3_div2_axis_clock,hw_trigger_0,hw_trigger_en_0,hw_trigger_1,hw_trigger_en_1,hw_trigger_2,hw_trigger_en_2,hw_trigger_3,hw_trigger_en_3,s_axi_aclk,s_axi_aresetn";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s_axi AWADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_awaddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_awaddr : signal is "XIL_INTERFACENAME s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 57500000, ID_WIDTH 0, ADDR_WIDTH 20, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN rfdc_ex_s_axi_aclk, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi AWVALID";
  attribute X_INTERFACE_INFO of s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s_axi AWREADY";
  attribute X_INTERFACE_INFO of s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s_axi WDATA";
  attribute X_INTERFACE_INFO of s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi WVALID";
  attribute X_INTERFACE_INFO of s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s_axi WREADY";
  attribute X_INTERFACE_INFO of s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s_axi WSTRB";
  attribute X_INTERFACE_INFO of s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s_axi BRESP";
  attribute X_INTERFACE_INFO of s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi BVALID";
  attribute X_INTERFACE_INFO of s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s_axi BREADY";
  attribute X_INTERFACE_INFO of s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s_axi ARADDR";
  attribute X_INTERFACE_INFO of s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi ARVALID";
  attribute X_INTERFACE_INFO of s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s_axi ARREADY";
  attribute X_INTERFACE_INFO of s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s_axi RDATA";
  attribute X_INTERFACE_INFO of s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s_axi RRESP";
  attribute X_INTERFACE_INFO of s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi RVALID";
  attribute X_INTERFACE_INFO of s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s_axi RREADY";
  attribute X_INTERFACE_INFO of m00_tdata : signal is "xilinx.com:interface:axis:1.0 m00 TDATA";
  attribute X_INTERFACE_MODE of m00_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m00_tdata : signal is "XIL_INTERFACENAME m00, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m00_tvalid : signal is "xilinx.com:interface:axis:1.0 m00 TVALID";
  attribute X_INTERFACE_INFO of m00_tready : signal is "xilinx.com:interface:axis:1.0 m00 TREADY";
  attribute X_INTERFACE_INFO of s00_user_tdata : signal is "xilinx.com:interface:axis:1.0 s00 TDATA";
  attribute X_INTERFACE_MODE of s00_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s00_user_tdata : signal is "XIL_INTERFACENAME s00, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s00_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s00 TVALID";
  attribute X_INTERFACE_INFO of s00_user_tready : signal is "xilinx.com:interface:axis:1.0 s00 TREADY";
  attribute X_INTERFACE_INFO of m01_tdata : signal is "xilinx.com:interface:axis:1.0 m01 TDATA";
  attribute X_INTERFACE_MODE of m01_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m01_tdata : signal is "XIL_INTERFACENAME m01, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m01_tvalid : signal is "xilinx.com:interface:axis:1.0 m01 TVALID";
  attribute X_INTERFACE_INFO of m01_tready : signal is "xilinx.com:interface:axis:1.0 m01 TREADY";
  attribute X_INTERFACE_INFO of s01_user_tdata : signal is "xilinx.com:interface:axis:1.0 s01 TDATA";
  attribute X_INTERFACE_MODE of s01_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s01_user_tdata : signal is "XIL_INTERFACENAME s01, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s01_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s01 TVALID";
  attribute X_INTERFACE_INFO of s01_user_tready : signal is "xilinx.com:interface:axis:1.0 s01 TREADY";
  attribute X_INTERFACE_INFO of m02_tdata : signal is "xilinx.com:interface:axis:1.0 m02 TDATA";
  attribute X_INTERFACE_MODE of m02_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m02_tdata : signal is "XIL_INTERFACENAME m02, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m02_tvalid : signal is "xilinx.com:interface:axis:1.0 m02 TVALID";
  attribute X_INTERFACE_INFO of m02_tready : signal is "xilinx.com:interface:axis:1.0 m02 TREADY";
  attribute X_INTERFACE_INFO of s02_user_tdata : signal is "xilinx.com:interface:axis:1.0 s02 TDATA";
  attribute X_INTERFACE_MODE of s02_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s02_user_tdata : signal is "XIL_INTERFACENAME s02, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s02_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s02 TVALID";
  attribute X_INTERFACE_INFO of s02_user_tready : signal is "xilinx.com:interface:axis:1.0 s02 TREADY";
  attribute X_INTERFACE_INFO of m03_tdata : signal is "xilinx.com:interface:axis:1.0 m03 TDATA";
  attribute X_INTERFACE_MODE of m03_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m03_tdata : signal is "XIL_INTERFACENAME m03, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m03_tvalid : signal is "xilinx.com:interface:axis:1.0 m03 TVALID";
  attribute X_INTERFACE_INFO of m03_tready : signal is "xilinx.com:interface:axis:1.0 m03 TREADY";
  attribute X_INTERFACE_INFO of s03_user_tdata : signal is "xilinx.com:interface:axis:1.0 s03 TDATA";
  attribute X_INTERFACE_MODE of s03_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s03_user_tdata : signal is "XIL_INTERFACENAME s03, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s03_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s03 TVALID";
  attribute X_INTERFACE_INFO of s03_user_tready : signal is "xilinx.com:interface:axis:1.0 s03 TREADY";
  attribute X_INTERFACE_INFO of m10_tdata : signal is "xilinx.com:interface:axis:1.0 m10 TDATA";
  attribute X_INTERFACE_MODE of m10_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m10_tdata : signal is "XIL_INTERFACENAME m10, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m10_tvalid : signal is "xilinx.com:interface:axis:1.0 m10 TVALID";
  attribute X_INTERFACE_INFO of m10_tready : signal is "xilinx.com:interface:axis:1.0 m10 TREADY";
  attribute X_INTERFACE_INFO of s10_user_tdata : signal is "xilinx.com:interface:axis:1.0 s10 TDATA";
  attribute X_INTERFACE_MODE of s10_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s10_user_tdata : signal is "XIL_INTERFACENAME s10, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s10_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s10 TVALID";
  attribute X_INTERFACE_INFO of s10_user_tready : signal is "xilinx.com:interface:axis:1.0 s10 TREADY";
  attribute X_INTERFACE_INFO of m11_tdata : signal is "xilinx.com:interface:axis:1.0 m11 TDATA";
  attribute X_INTERFACE_MODE of m11_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m11_tdata : signal is "XIL_INTERFACENAME m11, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m11_tvalid : signal is "xilinx.com:interface:axis:1.0 m11 TVALID";
  attribute X_INTERFACE_INFO of m11_tready : signal is "xilinx.com:interface:axis:1.0 m11 TREADY";
  attribute X_INTERFACE_INFO of s11_user_tdata : signal is "xilinx.com:interface:axis:1.0 s11 TDATA";
  attribute X_INTERFACE_MODE of s11_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s11_user_tdata : signal is "XIL_INTERFACENAME s11, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s11_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s11 TVALID";
  attribute X_INTERFACE_INFO of s11_user_tready : signal is "xilinx.com:interface:axis:1.0 s11 TREADY";
  attribute X_INTERFACE_INFO of m12_tdata : signal is "xilinx.com:interface:axis:1.0 m12 TDATA";
  attribute X_INTERFACE_MODE of m12_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m12_tdata : signal is "XIL_INTERFACENAME m12, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m12_tvalid : signal is "xilinx.com:interface:axis:1.0 m12 TVALID";
  attribute X_INTERFACE_INFO of m12_tready : signal is "xilinx.com:interface:axis:1.0 m12 TREADY";
  attribute X_INTERFACE_INFO of s12_user_tdata : signal is "xilinx.com:interface:axis:1.0 s12 TDATA";
  attribute X_INTERFACE_MODE of s12_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s12_user_tdata : signal is "XIL_INTERFACENAME s12, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s12_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s12 TVALID";
  attribute X_INTERFACE_INFO of s12_user_tready : signal is "xilinx.com:interface:axis:1.0 s12 TREADY";
  attribute X_INTERFACE_INFO of m13_tdata : signal is "xilinx.com:interface:axis:1.0 m13 TDATA";
  attribute X_INTERFACE_MODE of m13_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m13_tdata : signal is "XIL_INTERFACENAME m13, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m13_tvalid : signal is "xilinx.com:interface:axis:1.0 m13 TVALID";
  attribute X_INTERFACE_INFO of m13_tready : signal is "xilinx.com:interface:axis:1.0 m13 TREADY";
  attribute X_INTERFACE_INFO of s13_user_tdata : signal is "xilinx.com:interface:axis:1.0 s13 TDATA";
  attribute X_INTERFACE_MODE of s13_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s13_user_tdata : signal is "XIL_INTERFACENAME s13, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s13_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s13 TVALID";
  attribute X_INTERFACE_INFO of s13_user_tready : signal is "xilinx.com:interface:axis:1.0 s13 TREADY";
  attribute X_INTERFACE_INFO of m20_tdata : signal is "xilinx.com:interface:axis:1.0 m20 TDATA";
  attribute X_INTERFACE_MODE of m20_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m20_tdata : signal is "XIL_INTERFACENAME m20, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m20_tvalid : signal is "xilinx.com:interface:axis:1.0 m20 TVALID";
  attribute X_INTERFACE_INFO of m20_tready : signal is "xilinx.com:interface:axis:1.0 m20 TREADY";
  attribute X_INTERFACE_INFO of s20_user_tdata : signal is "xilinx.com:interface:axis:1.0 s20 TDATA";
  attribute X_INTERFACE_MODE of s20_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s20_user_tdata : signal is "XIL_INTERFACENAME s20, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s20_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s20 TVALID";
  attribute X_INTERFACE_INFO of s20_user_tready : signal is "xilinx.com:interface:axis:1.0 s20 TREADY";
  attribute X_INTERFACE_INFO of m21_tdata : signal is "xilinx.com:interface:axis:1.0 m21 TDATA";
  attribute X_INTERFACE_MODE of m21_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m21_tdata : signal is "XIL_INTERFACENAME m21, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m21_tvalid : signal is "xilinx.com:interface:axis:1.0 m21 TVALID";
  attribute X_INTERFACE_INFO of m21_tready : signal is "xilinx.com:interface:axis:1.0 m21 TREADY";
  attribute X_INTERFACE_INFO of s21_user_tdata : signal is "xilinx.com:interface:axis:1.0 s21 TDATA";
  attribute X_INTERFACE_MODE of s21_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s21_user_tdata : signal is "XIL_INTERFACENAME s21, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s21_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s21 TVALID";
  attribute X_INTERFACE_INFO of s21_user_tready : signal is "xilinx.com:interface:axis:1.0 s21 TREADY";
  attribute X_INTERFACE_INFO of m22_tdata : signal is "xilinx.com:interface:axis:1.0 m22 TDATA";
  attribute X_INTERFACE_MODE of m22_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m22_tdata : signal is "XIL_INTERFACENAME m22, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m22_tvalid : signal is "xilinx.com:interface:axis:1.0 m22 TVALID";
  attribute X_INTERFACE_INFO of m22_tready : signal is "xilinx.com:interface:axis:1.0 m22 TREADY";
  attribute X_INTERFACE_INFO of s22_user_tdata : signal is "xilinx.com:interface:axis:1.0 s22 TDATA";
  attribute X_INTERFACE_MODE of s22_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s22_user_tdata : signal is "XIL_INTERFACENAME s22, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s22_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s22 TVALID";
  attribute X_INTERFACE_INFO of s22_user_tready : signal is "xilinx.com:interface:axis:1.0 s22 TREADY";
  attribute X_INTERFACE_INFO of m23_tdata : signal is "xilinx.com:interface:axis:1.0 m23 TDATA";
  attribute X_INTERFACE_MODE of m23_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m23_tdata : signal is "XIL_INTERFACENAME m23, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m23_tvalid : signal is "xilinx.com:interface:axis:1.0 m23 TVALID";
  attribute X_INTERFACE_INFO of m23_tready : signal is "xilinx.com:interface:axis:1.0 m23 TREADY";
  attribute X_INTERFACE_INFO of s23_user_tdata : signal is "xilinx.com:interface:axis:1.0 s23 TDATA";
  attribute X_INTERFACE_MODE of s23_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s23_user_tdata : signal is "XIL_INTERFACENAME s23, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s23_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s23 TVALID";
  attribute X_INTERFACE_INFO of s23_user_tready : signal is "xilinx.com:interface:axis:1.0 s23 TREADY";
  attribute X_INTERFACE_INFO of m30_tdata : signal is "xilinx.com:interface:axis:1.0 m30 TDATA";
  attribute X_INTERFACE_MODE of m30_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m30_tdata : signal is "XIL_INTERFACENAME m30, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m30_tvalid : signal is "xilinx.com:interface:axis:1.0 m30 TVALID";
  attribute X_INTERFACE_INFO of m30_tready : signal is "xilinx.com:interface:axis:1.0 m30 TREADY";
  attribute X_INTERFACE_INFO of s30_user_tdata : signal is "xilinx.com:interface:axis:1.0 s30 TDATA";
  attribute X_INTERFACE_MODE of s30_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s30_user_tdata : signal is "XIL_INTERFACENAME s30, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s30_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s30 TVALID";
  attribute X_INTERFACE_INFO of s30_user_tready : signal is "xilinx.com:interface:axis:1.0 s30 TREADY";
  attribute X_INTERFACE_INFO of m31_tdata : signal is "xilinx.com:interface:axis:1.0 m31 TDATA";
  attribute X_INTERFACE_MODE of m31_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m31_tdata : signal is "XIL_INTERFACENAME m31, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m31_tvalid : signal is "xilinx.com:interface:axis:1.0 m31 TVALID";
  attribute X_INTERFACE_INFO of m31_tready : signal is "xilinx.com:interface:axis:1.0 m31 TREADY";
  attribute X_INTERFACE_INFO of s31_user_tdata : signal is "xilinx.com:interface:axis:1.0 s31 TDATA";
  attribute X_INTERFACE_MODE of s31_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s31_user_tdata : signal is "XIL_INTERFACENAME s31, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s31_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s31 TVALID";
  attribute X_INTERFACE_INFO of s31_user_tready : signal is "xilinx.com:interface:axis:1.0 s31 TREADY";
  attribute X_INTERFACE_INFO of m32_tdata : signal is "xilinx.com:interface:axis:1.0 m32 TDATA";
  attribute X_INTERFACE_MODE of m32_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m32_tdata : signal is "XIL_INTERFACENAME m32, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m32_tvalid : signal is "xilinx.com:interface:axis:1.0 m32 TVALID";
  attribute X_INTERFACE_INFO of m32_tready : signal is "xilinx.com:interface:axis:1.0 m32 TREADY";
  attribute X_INTERFACE_INFO of s32_user_tdata : signal is "xilinx.com:interface:axis:1.0 s32 TDATA";
  attribute X_INTERFACE_MODE of s32_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s32_user_tdata : signal is "XIL_INTERFACENAME s32, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s32_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s32 TVALID";
  attribute X_INTERFACE_INFO of s32_user_tready : signal is "xilinx.com:interface:axis:1.0 s32 TREADY";
  attribute X_INTERFACE_INFO of m33_tdata : signal is "xilinx.com:interface:axis:1.0 m33 TDATA";
  attribute X_INTERFACE_MODE of m33_tdata : signal is "master";
  attribute X_INTERFACE_PARAMETER of m33_tdata : signal is "XIL_INTERFACENAME m33, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m33_tvalid : signal is "xilinx.com:interface:axis:1.0 m33 TVALID";
  attribute X_INTERFACE_INFO of m33_tready : signal is "xilinx.com:interface:axis:1.0 m33 TREADY";
  attribute X_INTERFACE_INFO of s33_user_tdata : signal is "xilinx.com:interface:axis:1.0 s33 TDATA";
  attribute X_INTERFACE_MODE of s33_user_tdata : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s33_user_tdata : signal is "XIL_INTERFACENAME s33, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 307200000, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s33_user_tvalid : signal is "xilinx.com:interface:axis:1.0 s33 TVALID";
  attribute X_INTERFACE_INFO of s33_user_tready : signal is "xilinx.com:interface:axis:1.0 s33 TREADY";
  attribute X_INTERFACE_INFO of m0_axis_clock : signal is "xilinx.com:signal:clock:1.0 m0_axis_clock CLK";
  attribute X_INTERFACE_MODE of m0_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m0_axis_clock : signal is "XIL_INTERFACENAME m0_axis_clock, ASSOCIATED_BUSIF m00:s00:m01:s01:m02:s02:m03:s03, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m0_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 m0_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of m0_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m0_div2_axis_clock : signal is "XIL_INTERFACENAME m0_div2_axis_clock, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m1_axis_clock : signal is "xilinx.com:signal:clock:1.0 m1_axis_clock CLK";
  attribute X_INTERFACE_MODE of m1_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m1_axis_clock : signal is "XIL_INTERFACENAME m1_axis_clock, ASSOCIATED_BUSIF m10:s10:m11:s11:m12:s12:m13:s13, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m1_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 m1_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of m1_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m1_div2_axis_clock : signal is "XIL_INTERFACENAME m1_div2_axis_clock, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m2_axis_clock : signal is "xilinx.com:signal:clock:1.0 m2_axis_clock CLK";
  attribute X_INTERFACE_MODE of m2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m2_axis_clock : signal is "XIL_INTERFACENAME m2_axis_clock, ASSOCIATED_BUSIF m20:s20:m21:s21:m22:s22:m23:s23, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m2_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 m2_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of m2_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m2_div2_axis_clock : signal is "XIL_INTERFACENAME m2_div2_axis_clock, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m3_axis_clock : signal is "xilinx.com:signal:clock:1.0 m3_axis_clock CLK";
  attribute X_INTERFACE_MODE of m3_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m3_axis_clock : signal is "XIL_INTERFACENAME m3_axis_clock, ASSOCIATED_BUSIF m30:s30:m31:s31:m32:s32:m33:s33, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m3_div2_axis_clock : signal is "xilinx.com:signal:clock:1.0 m3_div2_axis_clock CLK";
  attribute X_INTERFACE_MODE of m3_div2_axis_clock : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m3_div2_axis_clock : signal is "XIL_INTERFACENAME m3_div2_axis_clock, FREQ_HZ 307200000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_rfip_0_clk_dac3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_aclk : signal is "xilinx.com:signal:clock:1.0 s_axi_aclk CLK";
  attribute X_INTERFACE_MODE of s_axi_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_aclk : signal is "XIL_INTERFACENAME s_axi_aclk, ASSOCIATED_BUSIF s_axi, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ 57500000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN rfdc_ex_s_axi_aclk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 s_axi_aresetn RST";
  attribute X_INTERFACE_MODE of s_axi_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_aresetn : signal is "XIL_INTERFACENAME s_axi_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "exdes_rfdac_data_bram_stim,Vivado 2025.1";
begin
end;
